### ISSUE TITLE
Epoll Not resoloved

### ISSUE THREAD

**Issue by Kwenma1** [OxideWaveLength/Minecraft-Hack-BaseClient#101]
I tried using this and it gives me an error that epoll cant be resolved to a type and the imports arent resolved because it doesn't know what epoll is I followed all the steps correctly yet It doesn't recognize it it also doesn't know what oshi import is.

**Comment by josephworks** [comment]
This is not an issue with this project. Please check your build path and project structure and make sure that the required libraries are present. Make sure you follow the tutorial or documentation properly.

**Comment by Kwenma1** [comment]
> This is not an issue with this project. Please check your build path and project structure and make sure that the required libraries are present. Make sure you follow the tutorial or documentation properly.

I did follow everything correctly but where can I find epoll? cos in the build path everything is there except for anything that has epoll

**Comment by Kwenma1** [comment]
Never mind i had the wrong mcp version installed.
