### ISSUE TITLE
[BUG] java is terminating the application.

### ISSUE THREAD

**Issue by AirRhyme** [OxideWaveLength/Minecraft-Hack-BaseClient#102]
**Describe the bug**
When I boot the application. It crashes almost instantly.

**Expected behavior**
Java will close randomly.

**Versions:**
 Windows 11
 Java 1.8 311
 Eclipse
 - Commit / Release: [Commit SHA-Hash or Release SHA-Has (if possible, else Commit number or Release version)]

**Comment by josephworks** [comment]
First, Nice intent.store pfp. I actually work with the guy.

Second, please take a moment that no one is able to help you with the information provided. You must attach some logs or screenshots better indicating the error.

**Comment by AirRhyme** [comment]
You wanted logs. It just shuts down. As for pictures... 
![console](https://user-images.githubusercontent.com/84876147/160240272-51ed4cde-f69f-439d-aaa6-2d573f52d969.png)
![refrences](https://user-images.githubusercontent.com/84876147/160240273-22fac040-8c87-4f9f-9a63-55d85dc95006.png)

**Comment by josephworks** [comment]
That looks like it isn't even starting up. Unfortunately, there isn't enough information for me to assist you, but I do not believe that that is an issue with this project, rather your IDE or configuration.

**Comment by AirRhyme** [comment]
I checked the IDE config and even did a fresh install, that has done nothing
nothing at all.
IF it helps this happened while I was cleaning off my disk.

**Comment by AirRhyme** [comment]
Apon further inspection, I decided to try IntelliJ. Intresting results...
![Screenshot 2022-04-16 160014](https://user-images.githubusercontent.com/84876147/163689688-b69d44d5-5eaf-441c-ba28-6a4b4ac00728.png)
any idea what 77 is??

**Comment by OxideWaveLength** [comment]
Sorry, I only just received the notification for this issue.
What class are you starting the client from?

**Comment by AirRhyme** [comment]
Start.java

**Comment by OxideWaveLength** [comment]
That is the correct class. It seems like the error 77 is a permission denied error.
I would make sure the path to the mcp does not contain special characters (exclamation marks included) and that you have full read/write permission to the folder

**Comment by AirRhyme** [comment]
this is in my base user directory, and Its just called Minecraft Client

**Comment by OxideWaveLength** [comment]
Try launching without debugging. Did you also specify the classpath in your profile? It needs to be manually done in IntelliJ

**Comment by AirRhyme** [comment]
I do not know how to do that

**Comment by OxideWaveLength** [comment]
I will provide you with the instructions in just a moment

**Comment by AirRhyme** [comment]
thanks

**Comment by OxideWaveLength** [comment]
Modify your launch profile and add this to the vm options:
`-Djava.library.path=versions/1.8.8/1.8.8-natives`

**Comment by AirRhyme** [comment]
ok

**Comment by AirRhyme** [comment]
it just ignored it

**Comment by AirRhyme** [comment]
`Completely ignored arguments: [-Djava.library.path=versions/1.8.8/1.8.8-natives]`

**Comment by OxideWaveLength** [comment]
Can you send a screenshot of the profile?

**Comment by AirRhyme** [comment]
![Screenshot 2022-04-17 120030](https://user-images.githubusercontent.com/84876147/163722575-c8e75211-0a29-4883-9ac6-394922f3e7b8.png)

**Comment by OxideWaveLength** [comment]
Hold on, there might be some extra steps involved in setting up the client to run in Intellij. Youtube took the video down not too long ago so I will have to re-upload it as soon as I have access to a computer. It shouldn't take longer than a couple of hours, I will send you the link as soon as I get that sorted out

**Comment by AirRhyme** [comment]
thank you!

**Comment by AirRhyme** [comment]
I also tried with eclipse and get the same result

**Comment by OxideWaveLength** [comment]
It unfortunately was harder than anticipated to retrieve the original video. I now have it and will upload it on YouTube as unlisted, waiting for the original's claim to be resolved (hopefully). I will link it here as soon as it is done uploading

**Comment by OxideWaveLength** [comment]
YouTube automatically flags the video as "inappropriate content". I may have to upload it on another website.

**Comment by OxideWaveLength** [comment]
Here it is: https://streamable.com/8rh46r
Not sure how long it will stay up for, don't really know the service either.
Keep in mind to set the path argument as shown in the video: `-Djava.library.path=versions/1.8.8/1.8.8-natives`
