### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Ihaveatrashaim** [OxideWaveLength/Minecraft-Hack-BaseClient#104]

**Comment by splatboy20081** [comment]
Well, isn’t this helpful.

**Comment by JonnyOnline** [comment]
Pls delete this

**Comment by josephworks** [comment]
Oxid, update the coming soon plz.

LOL

**Comment by josephworks** [comment]
Gus, the coming soon isn't updated.

**Comment by josephworks** [comment]
> Well, isn’t this helpful.

Nah, I just checked the current version of coming soon and it is saying that it is out of date.

Oxide please fix

**Comment by josephworks** [comment]
> Pls delete this

If we do that, then we may forget to update the coming soon.

**Comment by Ihaveatrashaim** [comment]
> > Pls delete this
> 
> If we do that, then we may forget to update the coming soon.

EDITED : well for someone that want join multi verison ,check this out : https://github.com/Foreheadchann/ViaMCP-Reborn and about clickgui check this one out, replace it with old one : https://github.com/DarkStorm652/Minecraft-GUI-API

**Comment by josephworks** [comment]
Everyone knows about those, and you shouldn't use DarkStorm GUI API if you know what you are doing.

**Comment by caillous-boyfriend** [comment]
yall are the fattest skids ever, just rewrite this stuff yourselves and you wont need to ask for an update
