### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#22]
**Is there it possible that you can make it use keys and not keycode in module so i dont have to look up like B is 66 or whatever it is.**

**Able to do so it shows no anticheat if its not an anti-cheat module like ESP or Fullbright etc.**

**ClickGUI** **_(maybe)_**

**Comment by OxideWaveLength** [comment]
About the key binding, you can use `org.lwjgl.input.Keyboard.KEY_B` instead, which is the B key

The AntiCheat the [modules arraylist](https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/wiki/Modules-ArrayList-(or-%22ToggledModules%22)) will be shown only if it's not Vanilla, if you mean in the TabGUI, I may work on that as well

About the ClickGUI, I might work on that later on

**Comment by OxideWaveLength** [comment]
If your issue has been solved you can close this issue
