### ISSUE TITLE
suggestion: TabList Menu

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#26]
Can you do so you can enable/disable the extra config menu: 
![image](https://user-images.githubusercontent.com/31127327/74090343-71a8b900-4aaa-11ea-9a92-a1a3212f966a.png)

Like if a module doesnt have any settings. So you can't go into it unless its enabled because you have putted something in it.

**Comment by OxideWaveLength** [comment]
Thanks for reporting this issue, I will work on that; I suggest you updating the TabGUI, now the module settings can be changed from there and the "enabled" and "key" settings are not displayed there anymore

**Comment by OxideWaveLength** [comment]
I am about to commit a fix for this bug, thanks for reporting it!
