### ISSUE TITLE
Hud Suggestion

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#28]
Make an example on how to make huds like ArmorStatus

_Totally not just because i can't figure it out and i have spent 4 hours trying..._

**Comment by OxideWaveLength** [comment]
I am sorry you had issues with that! I will make an example on how create huds, and show how to display minecraft items on the screen

**Comment by mymonsterdk** [comment]
thank you very much. 🥇

**Comment by OxideWaveLength** [comment]
Ok, I spent the last 1 hour trying to figure this out as well.. Apparently the only issue with my approach to rendering items on the screen was that I was trying to do that on a render3D event instead of a render2D... I literally went in every class that had to do with rendering, but my code was right, it was just the event..

Well, now I've got everything sorted out, and added into the RenderUtils, I will commit my changes and make the examples in the wiki!

**Comment by mymonsterdk** [comment]
Thank you :3

**Comment by mymonsterdk** [comment]
btw is there any possibility that i can get your code for it? or do i have to wait for the wiki update?

**Comment by OxideWaveLength** [comment]
https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/wiki/Create-a-HUD! I just finished adding the wiki page, you can follow the EventListener example, and instead of extending "EventListener" you extend "Module" (you also need to register the module in the ModuleManager#registerModules())

**Comment by mymonsterdk** [comment]
ok i will try and see if i can figure it out. Never played with this before so yeah xD thats why i wanted the code for armorstatus to see how it could be done and learn from that

**Comment by OxideWaveLength** [comment]
This is how you can draw an item from the `onRender2D()` method (which is the same on both EventListener and Module)

```Java
@Override
public void onRender2D(Render2DEvent event) {
	RenderUtils.renderItem(xPos, yPos, itemStack);
}
```

xPos is an int, and it is the x position (so the horizontal axis), from left, where the item will be rendered
yPos is the same as xPos, but vertical
itemStack is the itemstack, in your case  mc.thePlayer.getCurrentArmor(3) for the helmet (I highly suggest you to add a NullPointerException check)

**Comment by mymonsterdk** [comment]
ey it work's thanks :3
