### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#29]
Maybe you should make a discord people can join.

**Comment by OxideWaveLength** [comment]
Yes, I really think I should. I will do that by tomorrow, maybe a bot for that could be created as well, just to synchronize issues between GitHub and a Discord channel

**Comment by mymonsterdk** [comment]
yeah. Should i leave this issue open so you can send a link or?

**Comment by OxideWaveLength** [comment]
Yeah, I will close it once I create the server

**Comment by OxideWaveLength** [comment]
This is the new Discord: https://discord.gg/pDweRGz
