### ISSUE TITLE
MODULE BUG

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#31]
the module are still active when joining but they ain't doing anything so i have to reenable them

**Comment by OxideWaveLength** [comment]
This issue has been fixed in [this commit](https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/commit/6f69486b90d4e5ac6f4aab724793fd6b4b4e7724), replace the Module#loadFromSettings() method with this code:

``` Java
private void loadFromSettings() {
	if (moduleSettings.getBoolean("toggled")) {
		toggled = true;
		BaseClient.instance.getEventManager().registerListener(this);
	}

	this.key = moduleSettings.getInt("key");
	this.antiCheat = AntiCheat.valueOf(moduleSettings.getString("anticheat").toUpperCase());
	this.antiCheat = (Arrays.stream(allowedAntiCheats).anyMatch(antiCheat::equals) ? antiCheat : allowedAntiCheats[0]);
}
```

If you still have issues with it, you can re-open this issue
