### ISSUE TITLE
Update to 2020

### ISSUE THREAD

**Issue by Shyrogan** [OxideWaveLength/Minecraft-Hack-BaseClient#44]
Hey can we update the client to 2020 pls, thanks!!!

**Comment by OxideWaveLength** [comment]
Hi, I'm not quite sure about what you mean by that, could you please elaborate?

**Comment by mymonsterdk** [comment]
> Hey can we update the client to 2020 pls, thanks!!!

WYM? it is up to date

**Comment by OxideWaveLength** [comment]
Are you referring to the Minecraft version being 1.8.8 instead of 1.16?

**Comment by Shyrogan** [comment]
noob!

**Comment by tommy1235** [comment]
what the fuck-

**Comment by Camzure** [comment]
i agree. you are a noob.
