### ISSUE TITLE
How to Add the javaws.jar to your project buildpath

### ISSUE THREAD

**Issue by ZenoMilk12** [OxideWaveLength/Minecraft-Hack-BaseClient#47]
i do not know how to add the javaws.jar to my project buildpath in eclipse.
please help!

**Comment by OxideWaveLength** [comment]
The process can be seen in [this video](https://youtu.be/LSKu_zhPKc8?t=133) (minute 2:13)
It is also the last step in the "[Let's get started](https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient#lets-get-started)" section, in the readme.

Let me know if you have any issue or if anything is unclear

**Comment by ZenoMilk12** [comment]
Ok it works now thanks!
But why is laggy?

**Comment by OxideWaveLength** [comment]
When does it lag exactly? And by lag do you mean fps drops or low fps in general? If the first one, when do the drop happen? If the latter, what is the fps difference between vanilla minecraft with optifine and this base client?
In conclusion, have you added any module or event handler in general to the client?

**Comment by OxideWaveLength** [comment]
Actually, could you open another issue providing those informations and your computer specs?
