### ISSUE TITLE
How to build like xxx-client.jar and xxx-client.json

### ISSUE THREAD

**Issue by Smile-Apple-0** [OxideWaveLength/Minecraft-Hack-BaseClient#48]
How to build like xxx-client.jar and xxx-client.json

**Comment by HyptexPvP** [comment]
Hey there, i have found a tutorial for a pvp client, but it shows how to export the client here it is! https://www.youtube.com/watch?v=wAfKwpXBWzY

**Comment by OxideWaveLength** [comment]
I will make a tutorial on it soon, releasing a json file as well

**Comment by OxideWaveLength** [comment]
https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/wiki/Exporting-the-client#JSon-File
