### ISSUE TITLE
Module does not toggle off

### ISSUE THREAD

**Issue by HyptexPvP** [OxideWaveLength/Minecraft-Hack-BaseClient#51]
Hello, im trying to disable a module but it stays on even tho it says its disabled, heres my code.

package me.wavelength.baseclient.module.modules.movement;

import net.minecraft.client.Minecraft;
import org.lwjgl.input.Keyboard;

import me.wavelength.baseclient.event.events.UpdateEvent;
import me.wavelength.baseclient.module.AntiCheat;
import me.wavelength.baseclient.module.Category;
import me.wavelength.baseclient.module.Module;

public class Fly extends Module {

	public Fly() {
		super("Fly", "Reach the outer skies!", Keyboard.KEY_F, Category.MOVEMENT, AntiCheat.AAC, AntiCheat.AGC, AntiCheat.VANILLA);
	}

	private boolean isFlying;
	private boolean allowFlying;

	@Override
	public void setup() {
		moduleSettings.addDefault("speed", 1.0D);
	}

	@Override
	public void onEnable() {

	}

	@Override
	public void onDisable() {
		mc.thePlayer.capabilities.allowFlying = allowFlying;
		mc.thePlayer.capabilities.isFlying = isFlying;
	}

	@Override
	public void onUpdate(UpdateEvent event) {
		switch(antiCheat) {
			case VANILLA: {
				double speed = moduleSettings.getDouble("speed");

				speed = speed * 2;

				mc.thePlayer.capabilities.isFlying = true;
				this.isFlying = mc.thePlayer.capabilities.isFlying;
				this.allowFlying = mc.thePlayer.capabilities.allowFlying;

				mc.thePlayer.capabilities.allowFlying = true;
				break;
			}
			case AAC: {

			}
		}
		

	}
}

**Comment by mhmSure** [comment]
```java
package me.wavelength.baseclient.module.modules.movement;

import net.minecraft.client.Minecraft;
import org.lwjgl.input.Keyboard;

import me.wavelength.baseclient.event.events.UpdateEvent;
import me.wavelength.baseclient.module.AntiCheat;
import me.wavelength.baseclient.module.Category;
import me.wavelength.baseclient.module.Module;

public class Fly extends Module {
    public Fly() {
        super("Fly", "Reach the outer skies!", Keyboard.KEY_F, Category.MOVEMENT, AntiCheat.AAC, AntiCheat.AGC, AntiCheat.VANILLA);
    }

    private boolean isFlying;
    private boolean allowFlying;

    @Override
    public void setup() {
        moduleSettings.addDefault("speed", 1.0D);
    }

    @Override
    public void onEnable() {

    }


    @Override
    public void onDisable() {
        mc.thePlayer.capabilities.allowFlying = allowFlying;
        mc.thePlayer.capabilities.isFlying = isFlying;
    }

    @Override
    public void onUpdate(UpdateEvent event) {
        switch(antiCheat) {
            case VANILLA: {
                double speed = moduleSettings.getDouble("speed");

                speed = speed * 2;

                this.isFlying = mc.thePlayer.capabilities.isFlying;
                this.allowFlying = mc.thePlayer.capabilities.allowFlying;

                mc.thePlayer.capabilities.isFlying = true;
                mc.thePlayer.capabilities.allowFlying = true;
                break;
            }
            case AAC: {

            }
        }
    }
}
```

Try this code instead
If it doesn't work add me on discord instead (Sh4dow#8080)

**Comment by HyptexPvP** [comment]
Thank you, it works now!
