### ISSUE TITLE
Not able to call events

### ISSUE THREAD

**Issue by Jefferson88999** [OxideWaveLength/Minecraft-Hack-BaseClient#52]
Hello, when i try to use the call function from the eventmanager it gives an error saying my event argument is wrong.
Even tough it is a valid event.

**Comment by OxideWaveLength** [comment]
Could you show me the code you're using to call the event? (copy-paste the not-working line here)

**Comment by Jefferson88999** [comment]
public float getBlockReachDistance() {
		PlayerReachEvent event = new PlayerReachEvent(this.currentGameType.isCreative() ? 5.0F : 4.5F);
		EventManager.call(event);
        return event.getRange();
    }

The method call(Event) in the type EventManager is not applicable for the arguments (PlayerReachEvent)

**Comment by OxideWaveLength** [comment]
Does your class `PlayerReachEvent` extend `Event` (or `CancellableEvent`)?

**Comment by Jefferson88999** [comment]
Damn, forgot to add it.
Thank you

**Comment by OxideWaveLength** [comment]
No worries, is it fixed now?
You could also create a PR to add the Reach event to the Base Client
