### ISSUE TITLE
TabGui disabling on its own

### ISSUE THREAD

**Issue by XeonLyfe** [OxideWaveLength/Minecraft-Hack-BaseClient#56]
So if I close the client and reopen it the tab gui disappears.

**Comment by OxideWaveLength** [comment]
Thanks for opening this issue, have you modified the way modules or configs work in any way? Have you moved stuff inside of the main class (BaseClient.java)?
I'm assuming that you do manage to open the TabGui and once the client is closed it's gone, is that correct?

**Comment by XeonLyfe** [comment]
So if i run the client for the first time no mods at all to the configs and stop it tehn restart it the tabgui isnt there

**Comment by XeonLyfe** [comment]
hmm this code is dead 

		if (transparent != null) {
	        for (int i=0;i<texWidth*texHeight*4;i+=4) {
	        	boolean match = true;
	        	for (int c=0;c<3;c++) {
	        		if (toInt(scratch.get(i+c)) != transparent[c]) {
	        			match = false;
	        		}
	        	}
	  
	        	if (match) {
	        		scratch.put(i+3, (byte) 0);
	           	}
	        }
	    }

**Comment by XeonLyfe** [comment]
![2020-12-04_03 33 49](https://user-images.githubusercontent.com/75469782/101134770-bebcc500-35bf-11eb-80b8-04320abe1ee7.png)

**Comment by OxideWaveLength** [comment]
> So if i run the client for the first time no mods at all to the configs and stop it then restart it the tabgui isnt there
Can you confirm that the tabgui is there before you close the client and that you haven't modified the main class nor the modules one?

**Comment by XeonLyfe** [comment]
I fixed it By Going into jars\BaseClient\modules\semi-hidden and changing the thing to true.
![eve](https://user-images.githubusercontent.com/75469782/101135302-7baf2180-35c0-11eb-8748-c8d9b6cfbfd6.JPG)

**Comment by OxideWaveLength** [comment]
So your tabgui wasn't toggled in the first place, to toggle it you can send ".toggle tabgui" in the chat
