### ISSUE TITLE
Issue with creating new modules. Really just need help understanding this

### ISSUE THREAD

**Issue by anonfoxer** [OxideWaveLength/Minecraft-Hack-BaseClient#57]
Heya. Not an issue with the client but an issue with the fork of it that I have as I'm trying to create new modules.

Whenever I try to import anything from Minecraft (i.e. `import import net.minecraft.util.Hand;`)
I get an error from Eclipse that says "The import net.minecraft.util.Hand cannot be resolved", and gives me the options of creatinew new classes in the package, an interface in the package, an annotation in the package, an enum in the package, as well as some other options including "Fix Setup".

When following a much less clear tutorial I was able to figure this issue out, but I am lost on how to fix this. Please, if you can, help me out here because this is wracking my brain.

![help me](https://user-images.githubusercontent.com/28207003/101839340-d3d9ac80-3b07-11eb-9405-2216d0d6b4a9.PNG)
![help me 2](https://user-images.githubusercontent.com/28207003/101839405-ef44b780-3b07-11eb-88b7-f4d28d683a30.PNG)

**Comment by josephworks** [comment]
Make sure you have versions/1.8.8/1.8.8.jar as a dependency.

**Comment by anonfoxer** [comment]
> Make sure you have versions/1.8.8/1.8.8.jar as a dependency.

How would I go about making sure of this in Eclipse?

**Comment by josephworks** [comment]
Check your build path and make sure it is set up correctly.

**Comment by anonfoxer** [comment]
> Check your build path and make sure it is set up correctly.

Thats kind of vague. 
But, regardless.
Checking my build path
1.8.8.jar is inside of the Libraries, as is JRE 1.8.

[Link to a screencap.](https://imgur.com/a/428nFYO)

**Comment by josephworks** [comment]
Try and create a new project and see if the same error occurs. Alternatively, you can give me a message on discord (josephworks#7908) and we can work on getting the issue fixed much quicker. The last option would be to share your whole project and have myself or another dev take a look.

**Comment by OxideWaveLength** [comment]
I'm closing the issue as it's been inactive for a long time. If you are still having this problem re-open the issue.
