### ISSUE TITLE
Addons

### ISSUE THREAD

**Issue by Minecodes** [OxideWaveLength/Minecraft-Hack-BaseClient#59]
Can you please add an addon manager? If you have added the addon (class) there, it will be loaded with the functions of MCP.

PS: It's like a own class in the client.

**Comment by josephworks** [comment]
Yes, https://github.com/josephworks/Matix/blob/mc-1.8/src/minecraft/de/paxii/clarinet/module/external/ExternalModuleLoader.java 

https://www.javassist.org/

I am guessing that you are thinking of external modules. If so, hopefully, the resources above help.

**Comment by OxideWaveLength** [comment]
A feature similar to this is in the planning and should come with the next major update of the client
