### ISSUE TITLE
Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by winterfoxxy** [OxideWaveLength/Minecraft-Hack-BaseClient#61]
`Unrecognized option: -Xincgc`

I'm using the Eclipse IDE for Java Developers - 2020-12

I get this error every time I try to run the client, anyone that can help?
![image](https://user-images.githubusercontent.com/73034556/104092947-4350d200-5255-11eb-9acf-ed6e5d6726b7.png)

**Comment by AverageComet250** [comment]
Go into run config and remove that from arguments

Thanks,
Shravan Mandava

________________________________

**Comment by OxideWaveLength** [comment]
https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/wiki/Common-issues#unrecognized-option--xincgc-eclipse
