### ISSUE TITLE
How To Export Client?

### ISSUE THREAD

**Issue by mtgsquad** [OxideWaveLength/Minecraft-Hack-BaseClient#62]
I Have Added And Modified My Client A Lot, I Just Want To Publish It Now. How Do I Get A .jar And .json To Export And Put In A Folder In My Versions Folder. If Anyone Can Figure Out How To, Then Tell Me Please. You May Email Me [Here](mailto:mtgissmart@gmail.com).

**Comment by Pixchure** [comment]
you need decompiled MCP (when i tried to decompile mcp or recompile it it didnt work)

**Comment by mtgsquad** [comment]
> m

i have done the recompile thingy and I have set it up, but the issue is that I need to export it. like if you go to 1.8.8 in ur version folder, u see a jar and a .json file. i need those 2 files.

**Comment by Pixchure** [comment]
I think I know where to get the JSON file but not the jar :/

**Comment by AverageComet250** [comment]
Are you in eclipse or intellij

**Comment by mtgsquad** [comment]
> See 'exporting the client' in the wiki.

saw it. tried it. dint work. shows virtual machine error...

**Comment by AverageComet250** [comment]
Can you post a build log please

**Comment by mtgsquad** [comment]
> Can you post a build log please
Bruh... I Exported It. it Was Built Fine But, I Couldn't Launch It Through My MC Launcher

**Comment by AverageComet250** [comment]
Follow the instructions for getting the JSON file there too and then try launching it.

**Comment by mtgsquad** [comment]
> Follow the instructions for getting the JSON file there too and then try launching it.

I'm using the correct json file. the issue is that it just shows a jni our java virtual machine launcher

**Comment by AverageComet250** [comment]
Can you post the crash log then.

**Comment by mtgsquad** [comment]
> Can you post the crash log then.

Where is The Crash Log Stored? I'm Using TLauncher Tho...

**Comment by AverageComet250** [comment]
you're supposed to use it in the vanilla launcher.

try running it there and if it fails post the crash log

**Comment by mtgsquad** [comment]
> 
> 
> you're supposed to use it in the vanilla launcher.
> 
> try running it there and if it fails post the crash log

k

**Comment by OxideWaveLength** [comment]
Are you still facing issues?
