### ISSUE TITLE
i have made my own flys like hypixel verus and mineplex and this but idk how to add it all in to just fly so i dont have to have other modules so i can just go on to fly and then make it so u can choice what version u want it on

### ISSUE THREAD

**Issue by Meerz1337** [OxideWaveLength/Minecraft-Hack-BaseClient#64]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Stack Trace**
Add the error stack trace, if any.

**Versions:**
 - OS: [e.g. Windows 10]
 - Java: [e.g. JDK1_8, JRE1_8]
 - IDE: [e.g. Eclipse]
 - Commit / Release: [Commit SHA-Hash or Release SHA-Has (if possible, else Commit number or Release version)]

**Additional context**

**Comment by OxideWaveLength** [comment]
You can use the anticheat enum. Check whether the current anticheat is set to Hypixel and execute your hypixel code. You can add the anticheat list in the constructor. The [Fly](https://github.com/OxideWaveLength/Minecraft-Hack-BaseClient/blob/master/minecraft/me/wavelength/baseclient/module/modules/movement/Fly.java) has an example on how to do the latter part
