### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by RedmanPvPz** [OxideWaveLength/Minecraft-Hack-BaseClient#65]
Can anybody tell me how do i edit a premade hacked client. 
I want to change its code a bit, it is in .jar extension
I want to make it such that no ss tool can detect it, I will do it by changing its code a bit

**Comment by AverageComet250** [comment]
Either use fernflower (https://www.github.com/fesh0r/fernflower) to decompile it, and eclipse to edit it or just straight up open it in intellij idea as it has fernflower built into it.

**Comment by OxideWaveLength** [comment]
https://www.youtube.com/watch?v=LSKu_zhPKc8
