### ISSUE TITLE
Commercial use?

### ISSUE THREAD

**Issue by TomJuri** [OxideWaveLength/Minecraft-Hack-BaseClient#67]
I think the Title says all.

**Comment by OxideWaveLength** [comment]
The code is licensed under the MIT License.
https://choosealicense.com/licenses/mit/
https://softwareengineering.stackexchange.com/questions/255227/meaning-of-mit-license

**Comment by OxideWaveLength** [comment]
One quick thing I wanted to add, be sure to not distribute a jar if you're going to sell a modified version of the client. You should implement something similar to Jigsaw or Optifine (or Spigot, for that matter). Using diff files, distributing Minecraft's source code is against their EULA and against the law

**Comment by TomJuri** [comment]
OK Thx
