### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RealDaMotherYeeter** [OxideWaveLength/Minecraft-Hack-BaseClient#72]
Come on, idk why this is happening and it's annyoing

`C:\Users\244910\AppData\Roaming\Correto\jre\bin\java.exe -Djava.library.path=../libraries/1.8.8-natives "-javaagent:C:\Users\244910\AppData\Local\JetBrains\IntelliJ IDEA Community Edition 2020.3.2\lib\idea_rt.jar=56967:C:\Users\244910\AppData\Local\JetBrains\IntelliJ IDEA Community Edition 2020.3.2\bin" -Dfile.encoding=windows-1252 -classpath C:\Users\244910\AppData\Roaming\Correto\jre\lib\charsets.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\access-bridge-64.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\cldrdata.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\dnsns.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\jaccess.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\jfxrt.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\localedata.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\nashorn.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\sunec.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\sunjce_provider.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\sunmscapi.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\sunpkcs11.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\ext\zipfs.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\jce.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\jfr.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\jfxswt.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\jsse.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\management-agent.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\resources.jar;C:\Users\244910\AppData\Roaming\Correto\jre\lib\rt.jar;C:\Users\244910\Documents\minecraft-client\build\classes\java\main;C:\Users\244910\Documents\minecraft-client\build\resources\main;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\avutil-ttv-51.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\jinput-dx8.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\jinput-dx8_64.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\jinput-raw.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\jinput-raw_64.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\jinput-wintab.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\libmfxsw32.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\libmp3lame-ttv.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\lwjgl.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\lwjgl64.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\OpenAL32.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\OpenAL64.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\swresample-ttv-0.dll;C:\Users\244910\Documents\minecraft-client\libraries\1.8.8-natives\twitchsdk.dll;C:\Users\244910\Documents\minecraft-client\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\mojang\netty\1.6\netty-1.6.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\mojang\realms\1.7.39\realms-1.7.39.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\244910\Documents\minecraft-client\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\244910\Documents\minecraft-client\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\244910\Documents\minecraft-client\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\244910\Documents\minecraft-client\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\244910\Documents\minecraft-client\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\Users\244910\Documents\minecraft-client\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;C:\Users\244910\Documents\minecraft-client\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\244910\Documents\minecraft-client\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\244910\Documents\minecraft-client\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar;C:\Users\244910\Documents\minecraft-client\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\244910\Documents\minecraft-client\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar;C:\Users\244910\Documents\minecraft-client\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\244910\Documents\minecraft-client\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\244910\Documents\minecraft-client\libraries\slick.jar;C:\Users\244910\Documents\minecraft-client\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar;C:\Users\244910\Documents\minecraft-client\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar;C:\Users\244910\Documents\minecraft-client\libraries\tv\twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-64.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\javax.vecmath\vecmath\1.5.2\fd17bc3e67f909573dfc039d8e2abecf407c4e27\vecmath-1.5.2.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\org.slick2d\slick2d-core\1.0.2\54cb2b405b62aa4bebbfb7b61a830ee1c9852798\slick2d-core-1.0.2.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\javax.jnlp\jnlp\7.0\60ea74c5ee4dc5b22c74ea0300354cc2bc83bf4d\jnlp-7.0.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl\2.9.3\3df168ac74e4a8c96562cdff24ad352e255bf89c\lwjgl-2.9.3.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\org.jcraft\jorbis\0.0.17\8872d22b293e8f5d7d56ff92be966e6dc28ebdc6\jorbis-0.0.17.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.3\b1eafe80093381c56415731e1d64279e6140bcd0\lwjgl-platform-2.9.3-natives-linux.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.3\6686cf6ddaa20b4290aa6599a09bc0d17369be05\lwjgl-platform-2.9.3-natives-osx.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.3\fbc2afb3e288578e9942578decb6291a490549a0\lwjgl-platform-2.9.3-natives-windows.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput\2.0.5\39c7796b469a600f72380316f6b1f11db6c2c7c4\jinput-2.0.5.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\net.java.jutils\jutils\1.0.0\e12fe1fda814bd348c1579329c86943d2cd3c6a6\jutils-1.0.0.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\7ff832a6eb9ab6a767f1ade2b548092d0fa64795\jinput-platform-2.0.5-natives-linux.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\53f9c919f34d2ca9de8c51fc4e1e8282029a9232\jinput-platform-2.0.5-natives-osx.jar;C:\Users\244910\.gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\385ee093e01f587f30ee1c8a2ee7d408fd732e16\jinput-platform-2.0.5-natives-windows.jar Start
[17:42:14] [Client thread/INFO]: Setting user: WaveLength
[17:42:14] [Client thread/INFO]: (Session ID is token:0:WaveLength)
Exception in thread "Client thread" java.lang.ExceptionInInitializerError
	at net.minecraft.util.StatCollector.<clinit>(StatCollector.java:4)
	at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:267)
	at net.minecraft.item.Item.getItemStackDisplayName(Item.java:379)
	at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:506)
	at net.minecraft.item.ItemStack.getChatComponent(ItemStack.java:848)
	at net.minecraft.stats.StatList.initMiningStats(StatList.java:175)
	at net.minecraft.stats.StatList.init(StatList.java:127)
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:434)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:407)
	at net.minecraft.client.main.Main.main(Main.java:108)
	at Start.main(Start.java:7)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
	at net.minecraft.util.StringTranslate.<init>(StringTranslate.java:42)
	at net.minecraft.util.StringTranslate.<clinit>(StringTranslate.java:30)
	... 11 more
[17:42:16] [Client Shutdown Thread/INFO]: Stopping server

Process finished with exit code 1
`

**Comment by OxideWaveLength** [comment]
Have you started the decompiling process to let mcp copy minecraft's assets as shown in the IntelliJ installation video?

**Comment by RealDaMotherYeeter** [comment]
Yes, redid everything and it did not work

**Comment by josephworks** [comment]
I've seen this issue before. It usually has to do with the src/minecraft/assets dir. Make sure your Build Path or Project Structure is properly configured.

**Comment by josephworks** [comment]
@RealDaMotherYeeter is the issue fixed? This might be closed for inactivity if you don't respond.

**Comment by RealDaMotherYeeter** [comment]
I am using gradle and i fixed it with assets. Thank you!
