### ISSUE TITLE
eclipse run problem

### ISSUE THREAD

**Issue by k14ops** [OxideWaveLength/Minecraft-Hack-BaseClient#74]
it won't start

i have removed -Xincgc and when i did that this came up:

"Error: Could not find or load main class Start
Caused by: java.lang.ClassNotFoundException: Start"

**Comment by josephworks** [comment]
It can't find your Start.java. easy fix, check faq I think.

**Comment by OxideWaveLength** [comment]
What's the path to your MCP? Have you followed the tutorial closely?

**Comment by k14ops** [comment]
update it was as Josephworks said... thanks

**Comment by k14ops** [comment]
Close
