### ISSUE TITLE
[ERROR] Unrecognized option: -Xincgc

### ISSUE THREAD

**Issue by IuCC123** [OxideWaveLength/Minecraft-Hack-BaseClient#75]
When I try starting my project I keep on getting this error:

Unrecognized option: -Xincgc
![image](https://user-images.githubusercontent.com/80768059/112976304-00681180-9155-11eb-9c42-a70efbc8bfce.png)

Could anyone help me please or tell me how to fix this error,

Thanks,
IuCC

**Comment by IuCC123** [comment]
Got it fixed

**Comment by GitCat3** [comment]
what is it you did to fix? I am having the same problem

**Comment by josephworks** [comment]
Build Path, Arguments, Remove -Xincgc
