### ISSUE TITLE
Add script API from LiquidBounce

### ISSUE THREAD

**Issue by oceaann** [OxideWaveLength/Minecraft-Hack-BaseClient#81]
**Feature Description**
Add script API from LiquidBounce

**Feature Implementation**
Orginal API by CCBlueX:
https://github.com/CCBlueX/LiquidScript
(Also scripts need basics modules from liquidbounce)
Nice be gui for scripts and loading only selected folder with scripts (because lb starts few minutes when u got more then 20 scripts)

**Comment by OxideWaveLength** [comment]
Something similar is planned for the next version. It's not scripts, more like "mods". Will need to be written and compiled in Java.
