### ISSUE TITLE
[BUG] java: incompatible types: java.util.Iterator<java.lang.Object[]> cannot be converted to java.util.Iterator<T[]>

### ISSUE THREAD

**Issue by PixGuy** [OxideWaveLength/Minecraft-Hack-BaseClient#84]
Was following the Intellij Setup Tutorial when that happened
Screenshot:
https://media.discordapp.net/attachments/584392541336502283/874741681705091122/unknown.png
Full error message:
G:\Downloads Folder\7 4 2021\CrackByPaolloV\mcp918\src\minecraft\net\minecraft\util\Cartesian.java:61:36
java: incompatible types: java.util.Iterator<java.lang.Object[]> cannot be converted to java.util.Iterator<T[]>
im using Java 1.8

**Comment by josephworks** [comment]
I’d just like to mention how funny the CrackByPaolloV is.

Are you certain that this is an error with This project, cause this type of error would prevent the client from starting up (and I believe that this project can at least start up.
