### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by iProB1** [OxideWaveLength/Minecraft-Hack-BaseClient#89]
100 Errors 5 warnings 
about packages 
i did download java se development kit

**Comment by sigmaclientwastaken** [comment]
The repository is dead, it might take more than a week to get a response.

**Comment by josephworks** [comment]
Send screenshots and tell us your exact Java version.

Idk how you expect for us to help you based off of the information you provided.

@sigmaclientwastaken not true, you have been around for long enough to know that I am always active in responding to PRs and issues.

**Comment by sigmaclientwastaken** [comment]
> @sigmaclientwastaken not true, you have been around for long enough to know that I am always active in responding to PRs and issues.

While yes, you are active, sometimes it takes atleast a day for people to respond due to timezones and other reasons.

**Comment by josephworks** [comment]
Sure, but as long as I am here, it is far from dead.

**Comment by iProB1** [comment]
> Send screenshots and tell us your exact Java version.
> 
> Idk how you expect for us to help you based off of the information you provided.
> 
> @sigmaclientwastaken not true, you have been around for long enough to know that I am always active in responding to PRs and issues.

1.8.8 version 291

**Comment by AcaiBerii** [comment]
> Send screenshots and tell us your exact Java version.
> 
> Idk how you expect for us to help you based off of the information you provided.
> 
> @sigmaclientwastaken not true, you have been around for long enough to know that I am always active in responding to PRs and issues.

No response from either Oxide or you on my pull for 2 weeks. "always active"

**Comment by iProB1** [comment]
yea "always active"
im still waiting

**Comment by josephworks** [comment]
I couldn’t tell if this is serious or not, 1.8.8 Java doesn’t exist.

And in case you haven’t noticed, I am still waiting for you to send screenshots.
