### ISSUE TITLE
[BUG] Crashed instantly when opening exported version (normal launcher)

### ISSUE THREAD

**Issue by ncax** [OxideWaveLength/Minecraft-Hack-BaseClient#92]
**Describe the bug**
Whenever I opened the exported game, i get errors in the game output and a crash.

**To Reproduce**
Export the client, then launch from the normal launcher.

**Expected behavior**
A bunch of errors in the game output (can be enabled in the launcher settings) and a crash.

**Screenshots**
https://gyazo.com/2750c17fe0d32b4f145cbaa53d5d045e - Before Stacktrace
https://gyazo.com/95e6894af16c0a8f3236f2a211bb0abb - Stacktrace
https://gyazo.com/0f5714e276fe201a22757da047d17ae8 - Crash Report in the Launcher

**Stack Trace**
-- Head --
22:13:23.055
game
Stacktrace:
22:13:23.055
game
at net.minecraft.client.Minecraft.readImageToBuffer(Minecraft.java:800)
22:13:23.055
game
at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:682)
22:13:23.055
game
at net.minecraft.client.Minecraft.setWindowIcon(Minecraft.java:660)
22:13:23.055
game
at net.minecraft.client.Minecraft.startGame(Minecraft.java:498)
22:13:23.055
game
22:13:23.055
game
-- Initialization --
22:13:23.055
game
Details:
22:13:23.055
game
Stacktrace:
22:13:23.055
game
at net.minecraft.client.Minecraft.run(Minecraft.java:438)
22:13:23.055
game
at net.minecraft.client.main.Main.main(Main.java:108)

**Versions:**
 - OS: Windows 10
 - Java: JDK1_8, JRE1_8
 - IDE: Eclipse
 - Commit / Release: 74bf707

**Comment by Zaxiify** [comment]
Nevermind, I fixed it. I forgot to switch to Jre 1.8.

**Comment by HardShutdown** [comment]
close this issue

**Comment by josephworks** [comment]
@Zaxiify close this issue
