### ISSUE TITLE
MCP is unavaliable

### ISSUE THREAD

**Issue by PandaKingJnr** [OxideWaveLength/Minecraft-Hack-BaseClient#95]
The version of mcp that you have used is not archived anywhere and the only current version of mcp you can download is mcp910 from intent.store/getmcp
please provide a download for mcp916

**Comment by josephworks** [comment]
No, please use MCP 918

**Comment by PandaKingJnr** [comment]
where from
are you blind

**Comment by josephworks** [comment]
Oh, ur not bright. Have you tried googling it? Have you read the README?

No, you haven’t. This issue is your issue. You are the issue.

You probably shouldn’t be a client/software developer. Good luck!

**Comment by PandaKingJnr** [comment]
you know whats funny
theres no info about mcp on google(not really)

**Comment by PandaKingJnr** [comment]
https://please.rent-a-femboy.xyz/ineedmoney/zMSHJjA3

**Comment by PandaKingJnr** [comment]
![image](https://user-images.githubusercontent.com/76911797/144312266-b3bb34df-dbe6-40da-b2e5-1becb3e67ba5.png)

**Comment by josephworks** [comment]
> you know whats funny theres no info about mcp on google(not really)

![image](https://user-images.githubusercontent.com/18745823/144631112-16b0c9e4-0521-4a52-944e-2a03c0bb3e9e.png)

**Comment by JokersCat** [comment]
ahh to read this conversation is painful xD

**Comment by PandaKingJnr** [comment]
> 

for real i was actually dumb, i got brain now and realised that its not that way LOLOL
